---

- hosts: dns

  vars:
    unbound_access_control:
      - 10.0.0.0/8 allow
      - 127.0.0.0/8 allow
      - 192.168.0.0/16 allow
    unbound_conf_path: "/etc/unbound/unbound.conf.d/pi-hole.conf"
    unbound_control_enable: "yes"
    unbound_control_port: 8953
    unbound_do_ip6: "no"
    unbound_edns_buffer_size: 1472
    unbound_extended_statistics: "yes"
    unbound_harden_dnssec_stripped: "yes"
    unbound_harden_glue: "yes"
    unbound_interface_automatic: "yes"
    unbound_interfaces:
      - 0.0.0.0
    unbound_logfile: '"/var/log/unbound/unbound.log"'
    unbound_port: 5353
    unbound_prefer_ip6: "no"
    unbound_prefetch: "yes"
    unbound_private_addresses:
      - 192.168.0.0/16
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 10.0.0.0/8
      - fd00::/8
      - fe80::/10
    unbound_root_hints: '"/var/lib/unbound/root.hints"'
    unbound_so_rcvbuf: 1m
    unbound_statistics_cumulative: "no"
    unbound_statistics_interval: 0
    unbound_use_caps_for_id: "no"
    unbound_verbosity: 1

  roles:
  - anthony25.unbound

  become: true

  pre_tasks:
    - name: Install python-apt
      package:
        name: python-apt
        state: latest

    - name: Install unbound
      package:
        name: unbound
        state: latest

    - name: Download root hints
      become: true
      get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints

    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /var/log/unbound
        state: directory
        recurse: yes
        owner: unbound
        group: unbound
